#!/bin/bash
RED='\033[0;31m'
BROWN='\033[0;33m'
GRAY='\033[0;37m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color


# Function to display script usage
usage() {
    echo -e $CYAN"Usage:"$NC
    echo "  $0 -k				Kill virtual serial ports"
    echo "  $0 -s				verify if process is running"
    echo "  $0 -b [-ne] <baudrate>		Start virtual serial port with specified  baudrate."
    echo
    echo -e $GRAY"  (if 'ne' is specified, only outputs the ports when started instead of printing caption, ports and link)"$NC
    echo
    exit 1
}

getPorts(){
   local notext="$1"
   ls_output=$(ls -l --color=never /tmp/tty*)
    

    if [ "$notext" = false ]; then
        echo -e $CYAN"Virtual ports started on:"$NC
        echo -e "$ls_output" | grep -oP '(?=\/tmp).*'
    else
        echo -e "$ls_output" | grep -oP '\/tmp\/tty.{2}'
        
    fi
}

# Check if the script is called with valid options
if [ "$1" = "-k" ]; then

    # Check if the process exists
    if ! pgrep -x "socat" > /dev/null; then
        echo -e $GRAY"The target process is not running."$NC
        exit 1
    fi

    # Kill the target process
    killall socat
    echo -e $GRAY"process has been terminated succesfully."$NC
    exit 0
elif [ "$1" = "-s" ]; then

    # Check if the process exists
    if pgrep -x "socat" > /dev/null; then
        echo -e $BROWN"ProcessStatus:"$NC" running."
        getPorts false
    else 
        echo -e $BROWN"ProcessStatus:"$NC" stopped."
    fi
    exit 0
    
elif [ "$1" = "-b" ]; then


    if [ "$2" = "-ne" ]; then
    	baud=$3
    	notext=true
    else
        baud=$2
        notext=false
    fi
    
    # Check if the time argument is provided
    if [ -z "$baud" ]; then
        usage
    fi
    
    #check if socat is installed
    if ! command -v socat &> /dev/null
    then
        echo -e $RED"error: socat could not be found. Try 'sudo apt-get install -y socat'."$NC
        exit 1
    fi
    #check if argument is numeric
    re='^[0-9]+$'
    if ! [[ $baud =~ $re ]] ; then
       echo -e $RED"error: Not a number"$NC >&2;
       usage
       exit 1
    fi
    
    #check if its running
    if pgrep -x "socat" > /dev/null; then
        echo -e $RED"error: virtual serial port process is already running."$NC
        exit 1
    fi
    
    case $baud in
        9600|19200|115200)
	    baudOption="b$baud"
            socat pty,rawer,echo=0,link=/tmp/ttyV0,$baudOption pty,rawer,echo=0,link=/tmp/ttyV1,$baudOption &
	    ;;
        *)
            echo -e $RED"Invalid baudrate. Allowed values: 9600, 19200, 115200."$NC
            exit 1
            ;;
    esac
    
    sleep 0.5
    getPorts $notext

    exit 0

else
    usage
fi

